### ISSUE TITLE
api requests return empty list

### ISSUE THREAD

**Issue by ddoomenbsu** [pam-param-pam/Disney-Plus-api-wrapper#1]
Hi, from the half of this week I get empty lists returned when I search, do you experience this as well?
Been using it for a couple of weeks now and it worked great. But I can't seem to find where it is coming from...

**Comment by pam-param-pam** [comment]
Hi, 
Are you using the newest version?
If yes could you provide your code(including your search query) and tell me if theres any error or it just returns empty list?

**Comment by ddoomenbsu** [comment]
I've just tested with the latest version and this is the code I used and got an empty list.
Even if I keep it as simple as this
```python
from Config import APIConfig
from DisneyAPI import DisneyAPI

api = DisneyAPI(email="xxxxxx", password="xxxxxx")

title = input('What are you looking for? ')
searches = api.search(title)

for item in searches:
    print(f'{item.title}')
```

**Comment by pam-param-pam** [comment]
I just checked and everything works for me. If there were an IP block or if your account was flagged as suspicious, exceptions would have been raised. Keep in mind, passing an empty string or non-existent titles to the search() function will return an empty list.

Instead of using input(), I suggest trying a simple test like:
```python
print(api.search("loki"))
```
>>[Loki, The Making of Loki, The Good, The Bart, and The Loki, Moon Knight, Thor, Thor: The Dark World, The Mandalorian, Welcome to the Club, Marvel Studios' Thor: Ragnarok, WandaVision, Marvel Studios' Avengers: Infinity War, The Simpsons, Thor: Love and Thunder, Hawkeye, The Falcon and The Winter Soldier]

This way, we can confirm whether the issue lies within the library itself or elsewhere.
